version: "3.9"
services:
  worker:
    build: .
    environment:
      APP_ID: $11321821
      API_HASH: $bbf63cf902c2548c31963ccd88c4c6f7
      BOT_TOKEN: $5615063323:AAHzWuekv-wIvLHRJo3cOcAhj1daMZxsqEI
      OWNER: $5665936025
      THUMBNAIL: $THUMBNAIL
